


# I2C bus for VL53L0X (adjust pins if your board uses different pins)
i2c:
  sda: 26
  scl: 32
  scan: True

# Time-of-flight distance sensor
sensor:
  - platform: vl53l0x
    name: "VL53L0X Distance"
    update_interval: 0.5s
    timeout: 200ms
  

light:
  - platform: neopixelbus
    variant: WS2812
    pin: 27
    num_leds: 25
    type: GRB
    name: "Atom Matrix"
    id: atom_matrix
    color_correct: [100%, 100%, 100%] # The LED's on the Atom Matrix should not be run at full power
    #effects:
    #  - addressable_lambda:
    #      name: "Count 0-9"
    #      update_interval: 1s
    #      lambda: |-
    #        static const uint8_t digits[10][25] = {
    #          {1,1,1,1,1, 1,0,0,0,1, 1,0,0,0,1, 1,0,0,0,1, 1,1,1,1,1},
    #          {0,0,1,0,0, 0,1,1,0,0, 0,0,1,0,0, 0,0,1,0,0, 0,1,1,1,0},
    #          {1,1,1,1,1, 0,0,0,0,1, 1,1,1,1,1, 1,0,0,0,0, 1,1,1,1,1},
    #          {1,1,1,1,1, 0,0,0,0,1, 0,1,1,1,1, 0,0,0,0,1, 1,1,1,1,1},
    #          {1,0,0,1,0, 1,0,0,1,0, 1,1,1,1,1, 0,0,0,1,0, 0,0,0,1,0},
    #          {1,1,1,1,1, 1,0,0,0,0, 1,1,1,1,1, 0,0,0,0,1, 1,1,1,1,1},
    #          {1,1,1,1,1, 1,0,0,0,0, 1,1,1,1,1, 1,0,0,0,1, 1,1,1,1,1},
    #          {1,1,1,1,1, 0,0,0,0,1, 0,0,0,1,0, 0,0,1,0,0, 0,0,1,0,0},
    #          {1,1,1,1,1, 1,0,0,0,1, 1,1,1,1,1, 1,0,0,0,1, 1,1,1,1,1},
    #          {1,1,1,1,1, 1,0,0,0,1, 1,1,1,1,1, 0,0,0,0,1, 1,1,1,1,1}
    #        };
    #        static int idx = 0;
    #        for (int i = 0; i < 25; i++) {
    #          if (digits[idx][i]) it[i] = Color(255, 255, 255);
    #          else it[i] = Color::BLACK;
    #        }
    #        idx = (idx + 1) % 10;



